### ISSUE TITLE
Configuration Credentials in External File

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#18]
The `config.php` file holds the credentials for accessing the database. This works fine but it might be better to put the access crendetials in an external file in a json format and then to access the file from `config.php`. The format of the json file might be something like this:  
```
	"FCP_PROFILE_DB": {
	    "USER": "some_user",
	    "PWD": "some_pwd",
	    "HOST": "127.0.0.1",
	    "NAME": "some_name"
	}	
```
The advantage is that, when I update the FCP Edtitor installation or when I transfer it to others, I do not have to remember to remove or update the content of `config.php`.

**Comment by Tomas-M** [comment]
This can be done, but has some drawbacks.

Since the tool is open source, any user will know what file is used to store the database settings including password.
If it is stored for example in a file config.json, any stranger will be able to type in browser the URL address like http://domain.com/fcp-editor/config.json ... and the file will be downloaded, leaking the password. Users would be forced to make changes to webserver configuration in order to block the download of the file, which may be complicated for some users.

I would suggest different approach.
The file config.php will act as a template only, and the actual file which will be included will have different name, for example config_user.php ... And this file will never be part of the git tree, because it is untracked, thus user will never overwrite it with new upgrade.

So, when user installs the tool for the first time, he will need to rename (or copy) config.php to config_user.php and then edit the settings in config_user.php.

When the user updates the tool later, he will always have his existing config_user.php in place already.

Here is the diff for this change (cannot upload it directly here, and I am not sure if you agree with this proposed change)
If you like, I can push it to github right away.

```
diff --git a/DOCUMENTATION.install b/DOCUMENTATION.install
index bbbcda9..53e1c73 100644
--- a/DOCUMENTATION.install
+++ b/DOCUMENTATION.install
@@ -8,7 +8,8 @@ How to install:
 - Make sure that the 'tmp' directory is writable by all:
   chmod 0777 ./fcp-editor/tmp
 
-- Edit config.php file on server, for example ./fcp-editor/config.php
+- Rename config.php file on server to config_user.php,
+  for example ./fcp-editor/config_user.php
   and make sure to put there correct credentials for MySQL connection.
 
 - Make sure your database is already created. It doesn't need
diff --git a/Makefile b/Makefile
index 34f306b..527dcd1 100644
--- a/Makefile
+++ b/Makefile
@@ -8,4 +8,5 @@ sync:
 		--exclude='.git*' \
 		--exclude='*.patch' \
 		--exclude='config.php' \
+		--exclude='config_user.php' \
 		. p8258320@home34821896.1and1-data.host:pnp-software.com/fwprofile/editor-5.01/
diff --git a/inc_db.php b/inc_db.php
index bf49d2c..ec75600 100644
--- a/inc_db.php
+++ b/inc_db.php
@@ -22,7 +22,8 @@
   {
      GLOBAL $dbcon_link_db;
 
-     require('config.php'); // sql settings
+     // sql settings
+     require('config_user.php');
 
      // if mysql connection is not set, setup it now
      if (!$dbcon_link_db)
diff --git a/install.php b/install.php
index 46c59e7..642ccb8 100644
--- a/install.php
+++ b/install.php
@@ -1,7 +1,7 @@
 <?php
 
    require('inc_db.php');
-   require('config.php');
+   require('config_user.php');
 
    echo "Creating mysql tables (if not exist)... ";
 
diff --git a/users.php b/users.php
index fa4a18f..dde247b 100644
--- a/users.php
+++ b/users.php
@@ -3,7 +3,7 @@
    require_once('inc_db.php');
    require_once('inc_lib.php');
    require_once('inc_session.php');
-   require('config.php');
+   require('config_user.php');
 
    if (userID()!=$exampleUserID) die("You are not authorized to see this. Please login first.");
 
diff --git a/vars.php b/vars.php
index eb904ff..8bcaf4d 100644
--- a/vars.php
+++ b/vars.php
@@ -1,8 +1,8 @@
 <?php
-   require('config.php');
    require('version.php');
    require_once('inc_db.php');
    require_once('inc_lib.php');
+   require('config_user.php');
 
    header("Content-Type: text/javascript");
 ```

**Comment by pasetti** [comment]
Your proposed solution would be fine for me (and it would indeed remove the problem I had highlighted -- hence, feel free to upload it). But I still have one question about the first approach:

> Since the tool is open source, any user will know what file is used to store the database settings including password.
If it is stored for example in a file config.json, any stranger will be able to type in browser the URL address like http://domain.com/fcp-editor/config.json ... and the file will be downloaded, leaking the password. Users would be forced to make changes to webserver configuration in order to block the download of the file, which may be complicated for some users. 

What I had in mind was to put the database access credentials in a file in a location like /etc/fcp_editor or some other place which is outside the web root and therefore not accessible externally (or so I would expect). Is perhaps the problem that PHP has no access to files outside the web root?

**Comment by Tomas-M** [comment]
OK, changes pushed by ad1b0ae4c5998228ec83353f1b3c4932731ff09e

If  you put the credentials to an external file outside of web root, PHP can usually read it, but sometimes it cannot (depends on server settings). Main issue I see is that the *user* in many cases cannot write files outside of the web root, since many web hosts give you FTP access to the web root only, not outside of it. As usual it depends.

So putting the config to a PHP file which is not part of the git tree seems like a reasonable compromise.

**Comment by pasetti** [comment]
New feature has been tested and it works as intended.
