### ISSUE TITLE
Deleting SCOS Database

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#21]
When I log in as example user at `www.mydomain.com/users.php`, I have the option to load a new database. This works very well. At present, if I need to delete a previously loaded database, I do it through the MySQL interface. Would it possible to do it through the `www.mydomain.com/users.php` interface (perhaps by adding a 'delete' button in the list of installed SCOS databases)? 

PS: This request belongs to the 'nice-to-have' category since database deletion through the MySQL interface. Hence, if there is a complex change with a risk that this new feature might disrupt some existing function, we should thnk twice before doing it.

**Comment by Tomas-M** [comment]
Implemented by 4b494bcf4d4dd5fe20656b551aade7d67e52680c
It will allow only deletion of databases with SCOS_ prefix. Please keep in mind that the administrator must know what is he doing, when deleting a database, because some users may have been using it already in their diagrams (they will most likely lose the possibility to autocomplete on such diagrams unless they select different database)
