### ISSUE TITLE
Obsolete Action in "Manage Files" Modal

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fcp-editor#28]
When I select the "Files" button in the banner at the left side of the window, I get a modal pop-up which, at the very bottom, has an antry for: "Edit values which are assigned to transition identifiers". This entry is  left-over from the FW Profile Editor and, as far as I can tell, it is completely irrelevant to the FCP Editor. Can it be deleted?

**Comment by Tomas-M** [comment]
idMaps are used on many places, so removing it would involve lots of code changes.
Since the FCP editor is kinda unclean copy of FW Profile editor (eg. we do not have 100% clean code, there are other leftovers from the FW Profile editor), I will just hide the user interface, I won't modify the other code (can be safely ignored).
If you want me to properly cleanup everything to get rid of idMaps, let me know, but that will be much longer work.
Hidden now by 5f7aecca2f723871a656f3654ea020e3d7dcb44a

**Comment by pasetti** [comment]
OK. For the time being, we use the "unclean" solution. I will open a separate ticket for the cleaning up of the left-overs from the FW Profile.
